# Generated by Django 5.1.5 on 2025-03-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gdpr_consent',
            new_name='tc_consent',
        ),
    ]
