# Generated by Django 5.1.5 on 2025-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userprofile_two_factor_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="gdpr_consent",
            new_name="tc_consent",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="leafcoins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
