# Generated by Django 5.1.5 on 2025-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_gdpr_consent_userprofile_tc_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_games',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
